= Site (2.0)

Site is an open-source software platform offering:

* Data storage
* User authentication (including https://openid.net/[OpenID])
* Flexible access-control (https://en.wikipedia.org/wiki/Role-based_access_control[RBAC], https://en.wikipedia.org/wiki/Attribute-based_access_control[ABAC] and policy-based)
* Support for https://www.openapis.org/[OpenAPI] and https://graphql.org/[GraphQL] programmable APIs, with an https://github.com/babashka/SCI[embedded powerful language].
* A built-in OAuth2 Authorization Server for issuing access tokens
* Excellent conformance with standards (HTTP, OAuth2, OpenID) to maximise interoperability and minimize lock-in

On top of these features, Site has strong support for data governance.
Every state of the database is accessible at any point in time.
Every change to the database is auditable, so you can find out who made which change to the data, and when.

Similar
https://blog.boot.dev/backend/backend-as-a-service/[Backend-as-a-Service]
products are great for simple CRUD applications but don't work well
for more sophisticated use-cases.  Site is intended to handle the more
complex projects which many BaaS products can't.

== Status

Site 2.0 is not yet ready for evaluation and is in the process of
maturing. We are developing 'in the open', please treat this
repository in that spirit.

The previous 1.0 generation of Site is maintained at https://github.com/juxt/site.

== What is Site and how would I use it?

* You work for an organisation and want to provide a platform to
  developers which provides built-in benefits such as HTTP
  conformance, API security and a built-in database.

* You have a dataset that you want to make available to
  consumers/customers via a secure OAuth2-compliant API, but don't
  want to build a system from scratch.

* You are a Clojure developer building a new system to allow access to
  data over a REST API. You can use Site as a jump-start project,
  fulfilling a similar purpose to our
  https://github.com/juxt/edge[Edge] project.

In all these cases, https://juxt.pro[JUXT] can provide expert guidance, consulting and
development resources, if required. Contact info@juxt.pro to schedule
an appointment.

== Getting Started

. Clone this repository to your computer, cd into the `site` directory.
+
----
$ git clone https://github.com/juxt-site/site
$ cd site
----

. Ensure you have https://github.com/babashka/babashka[Babashka] version v1.1.172 or later installed.
+
----
site$ bb --version
babashka v1.1.172
----

. Copy `server/etc/config.edn` to `$HOME/.config/site/config.edn`
+
----
site$ mkdir -p $HOME/.config/site
site$ cp server/etc/config.edn $HOME/.config/site/config.edn
----
Review the config at `$HOME/.config/site/config.edn` and make any appropriate modifications.

. Start the Site instance
+
----
site$ server/bin/site-server
----

. Check the server starts up
+
----
Site by JUXT. Copyright (c) 2020-2023, JUXT LTD.
2023-05-22 11:02:46.508:INFO::main: Logging initialized @5804ms to org.eclipse.jetty.util.log.StdErrLog
----
+
----
site$ curl http://localhost:4444/_site/healthcheck
----
+
----
Site OK!
----

. Bootstrap your Site instance by deploying a minimal set of resources
+
----
site$ server/bin/site-bootstrap apply -c server/init/scripts/localhost/clean-eval-deploy.edn
----
+
Follow the prompts to bootstrap the system and add your initial user.

. With a browser, navigate to https://petstore.swagger.io/
.. Change the main text-input to http://localhost:4444/_site/openapi.json
.. Click on /whoami, 'Try it out' and 'Execute' (this should yield a `401 Error: Unauthorized`)
.. Click on 'Authorize', ensure client_id is set to `swagger-ui`, under Scopes, click on `select-all`
.. Login if necessary with the username/password that you entered when bootstrapping the system
.. If the login succeeded, click on `Close`.
.. Click again on `Execute` of the `/whoami` resource. This should now return a 200.


== (Old instructions)

NOTE: We're keeping these instructions as they're useful if you want
to configure a reverse-proxy with proper hostnames.

If you're really keen, you can try out Site and use Swagger UI as a test client.
Follow these instructions:

. Install nginx - see link:doc/next/Installation.adoc[]
. `git clone https://github.com/juxt-site/swagger-ui`
. Install `mkcert` as per link:doc/next/Installation.adoc[]
. Create a cert: `mkcert data.site.test auth.site.test`
. Create a separate cert for the Swagger UI client: `mkcert swagger-ui.site.test`
. Move the generated certs (and associated key files) to your `/etc/nginx/` directory.
. Add the following sub-section to the `http` section of your `/etc/nginx/nginx.conf` file
+
----
    server {
        listen       443 ssl;
        server_name  data.site.test auth.site.test;

        ssl_certificate      data.site.test+1.pem;
        ssl_certificate_key  data.site.test+1-key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
           proxy_pass	http://localhost:2021;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
----
. Add the following sub-section to the `http` section of your `/etc/nginx/nginx.conf` file
+
----
    server {
        listen       443 ssl;
        server_name  swagger-ui.site.test;

        ssl_certificate      swagger-ui.site.test.pem;
        ssl_certificate_key  swagger-ui.site.test-key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
	  # Replace this with the absolute path of the dist subdir of the swagger-ui clone
	  root swagger-ui/dist/;
        }
    }
----
. As noted, replace the `swagger-ui/dist/` line with the right location on your system.
. Make sure the `ssl_certificate` and `ssl_certificate_key` entries match the filenames of your cert and key files.
. Check nginx config with `nginx -t` first, which will also check the filenames are correct
. Start nginx, e.g. `sudo systemctl start nginx`
. Start a REPL using the provided deps.edn in the usual way.
. Go to the file `src/juxt/site/repl.clj` and search for `:openid/register-user`. Edit the settings there according to your GitHub username.
. From the REPL, enter `(init)`. Alternatively, `rlwrap ncat localhost 50505` and type `:init` - this step will require network access as it downloads issuer configuration and keys.
. Browse to https://swagger-ui.site.test/
. Click on the green `Authorize` button
. Initially this will redirect you to Auth0. Click on the Github icon which will take you to Github. You'll need to allow Github to authorize Auth0 to access your basic profile details. These are used to match the identity you've registered with `:open/register-user`.
. You should now be able to 'try out' the API operations in the Swagger UI.

== When would you use Site?

Site might be a good choice if one or more of the following apply:

* you are developing a browser-based web application but don't have time to develop the backend.
* you are developing an application and want to centralise common data such that it can be shared securely with other applications.
* you have strong requirements for security and access-control over your data.
* you want to access your data over web APIs, such as OpenAPI and/or GraphQL.
* you want to interatively prototype a web API.

== Testing

Run the tests with `make test` if you have make installed, or if not, with `clojure -M:test -m kaocha.runner test`.

== Technical Description

Site is a standards-compliant web server, fulfilling the roles of an https://www.rfc-editor.org/rfc/rfc6749[OAuth2] resource server and authorization server.

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
resource server:: The server hosting the protected resources, capable of accepting and responding to protected resource requests using access tokens.
--

Resources are documents which represent a resource's identity (URI), configuration and current state (which might be some data, image or other media).
Site stores resources in a database.

A resource request is a standard web request to a URI (as part of an API, such as https://www.openapis.org/[OpenAPI]) or https://graphql.org/[GraphQL] request.

Requests contain an access-token, acquired from an authorization server:

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
authorization server:: The server issuing access tokens to the client
after successfully authenticating the resource owner and obtaining
authorization.
--

Currently, the only supported database is JUXT's immutable https://xtdb.com[XTDB] database.
XTDB is a good fit for Site, since many of its features (such as document ids and references) map cleanly onto web concepts (such as URIs and links).

== Features

Current development is still focussed on the technical feature set, as required to conform to the relevant standards and provide good interoperability.

=== Resource Server

* Content Negotiation
* Conditional Requests
* Access Control (https://en.wikipedia.org/wiki/Role-based_access_control[RBAC], https://en.wikipedia.org/wiki/Attribute-based_access_control[ABAC] or policy based)
* GraphQL

=== Authorization Server

* Client Registration
* User Authentication (Basic, Login form, OpenID)
* OAuth2 access token grants

== Programming Site

Some types of resource, such as 'operations', may contain Site 'programs' that are executed when required.
All resources are stored in the database, including all program code.

Currently, the only available programming language is https://github.com/babashka/sci/[SCI].

== Consulting

Contact info@juxt.pro if you would like help, we can provide professional consulting services for Site and/or XTDB.

== References

- https://acropolium.com/blog/first-look-at-backend-as-a-service/

== License

The MIT License (MIT)

Copyright © 2020-2023 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
