= Site (2.0)

Site is an open-source runtime platform offering:

* Data storage
* User authentication (including https://openid.net/[OpenID])
* Flexible access-control (https://en.wikipedia.org/wiki/Role-based_access_control[RBAC], https://en.wikipedia.org/wiki/Attribute-based_access_control[ABAC] and policy-based)
* Support for https://www.openapis.org/[OpenAPI] and https://graphql.org/[GraphQL] programmable APIs, with an https://github.com/babashka/SCI[embedded powerful language].
* A built-in OAuth2 Authorization Server for issuing access tokens
* Excellent conformance with standards (HTTP, OAuth2, OpenID) to maximise interoperability and minimize lock-in

On top of these features, Site has strong support for data governance.
Every state of the database is accessible at any point in time.
Every change to the database is auditable, so you can find out who made which change to the data, and when.

Similar
https://blog.boot.dev/backend/backend-as-a-service/[Backend-as-a-Service]
products are great for simple CRUD applications but don't work well
for more sophisticated use-cases.  Site is intended to handle the more
complex projects which many BaaS products can't.

== Status

Site 2.0 is not yet ready for evaluation outside of JUXT, and is in
the process of maturing. We are developing 'in the open', please treat
this repository in that spirit.

The previous 1.0 generation of Site is maintained at https://github.com/juxt/site.

== Which types of projects might I use Site for?

* You want to get started on a project quickly, and there are
  requirements for the project to serve data over an API.

* You have a dataset that you want to make available to
  consumers/customers via a secure OAuth2-compliant API, but don't
  want to build a system from scratch.

In these cases, https://juxt.pro[JUXT] can provide expert guidance, consulting and
development resources, if required. Contact info@juxt.pro to schedule
an appointment.

== Getting Started

See https://github.com/juxt-site/book[this repository]

== When would you use Site?

Site might be a good choice if one or more of the following apply:

* you are developing a browser-based web application but don't have time to develop the backend.
* you are developing an application and want to centralise common data such that it can be shared securely with other applications.
* you have strong requirements for security and access-control over your data.
* you want to access your data over web APIs, such as OpenAPI and/or GraphQL.
* you want to interatively prototype a web API.

== Testing

Run the tests with `make test` if you have make installed, or if not, with `clojure -M:test -m kaocha.runner test`.

== Technical Description

Site is a standards-compliant web server, fulfilling the roles of an https://www.rfc-editor.org/rfc/rfc6749[OAuth2] resource server and authorization server.

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
resource server:: The server hosting the protected resources, capable of accepting and responding to protected resource requests using access tokens.
--

Resources are documents which represent a resource's identity (URI), configuration and current state (which might be some data, image or other media).
Site stores resources in a database.

A resource request is a standard web request to a URI (as part of an API, such as https://www.openapis.org/[OpenAPI]) or https://graphql.org/[GraphQL] request.

Requests contain an access-token, acquired from an authorization server:

[quote,https://www.rfc-editor.org/rfc/rfc6749#section-1.1]
--
authorization server:: The server issuing access tokens to the client
after successfully authenticating the resource owner and obtaining
authorization.
--

Currently, the only supported database is JUXT's immutable https://xtdb.com[XTDB] database.
XTDB is a good fit for Site, since many of its features (such as document ids and references) map cleanly onto web concepts (such as URIs and links).

== Features

Current development is still focussed on the technical feature set, as required to conform to the relevant standards and provide good interoperability.

=== Resource Server

* Content Negotiation
* Conditional Requests
* Access Control (https://en.wikipedia.org/wiki/Role-based_access_control[RBAC], https://en.wikipedia.org/wiki/Attribute-based_access_control[ABAC] or policy based)
* GraphQL

=== Authorization Server

* Client Registration
* User Authentication (Basic, Login form, OpenID)
* OAuth2 access token grants

== Programming Site

Some types of resource, such as 'operations', may contain Site 'programs' that are executed when required.
All resources are stored in the database, including all program code.

Currently, the only available programming language is https://github.com/babashka/sci/[SCI].

== Consulting

Contact info@juxt.pro if you would like help, we can provide professional consulting services for Site and/or XTDB.

== References

- https://juxt.slides.com/malcolmsparks/atomic-architecture
- https://www.juxt.pro/blog/atomic-architecture/
- https://www.juxt.pro/blog/site-safari/
- https://podcasts.apple.com/us/podcast/clojurestream-podcast/id1461500416
- https://www.oauth.com/
- https://acropolium.com/blog/first-look-at-backend-as-a-service/

== License

The MIT License (MIT)

Copyright © 2020-2023 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
