= Getting Started
:toc: left
:clj-version: 1.11.1
:bb-version: 1.1.172
:gum-version: 0.10.0
:curl-version: 8.0.0
:java-version: 17

Follow this guide to get up-and-running with your very own Site instance, running locally on your machine.
If you wish to install Site in production, refer to <<ch-installation>>.

=== Dependencies

Before we get started, let's check some dependencies.

<<gs-dependencies>> shows a table of dependencies that we will need to install before we can get started with Site.

[[gs-dependencies]]
.Required dependencies
[options=header,unbreakable,cols="3,3,5m"]
|===
|Name|Command|Minimum version
|java|java|{java-version}
|Clojure|clj|{clj-version}
|Babashka|bb|{bb-version}
|gum|gum|{gum-version}
|curl|curl|{curl-version}
|===

==== Java

Site runs on the JVM, and requires a modern installation.

----
java -version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
----

==== Clojure

Site is written in Clojure, and requires Clojure to be installed on your machine.
Ensure you have https://clojure.org/[Clojure] version v{clj-version} or later installed:

----
clj --version
Clojure CLI version 1.11.1.1273
----

==== Babashka

Site uses Babashka for some tools and scripting.
Ensure you have https://github.com/babashka/babashka[Babashka] version v{bb-version} or later installed:

----
bb --version
babashka v1.1.172
----

==== gum

Some of Site's scripts make use of https://github.com/charmbracelet/gum/[`gum`], which gives a nicer command-line experience.
Ensure you have `gum` installed.

----
gum --version
gum version 0.10.0 (0f0f8e9)
----

For example, on Arch Linux you can install `gum` with the following:

----
pacman -S gum
----

==== curl (optional)

For testing certain operations, we will be using https://curl.se/[`curl`].
Check you have `curl` on your system

----
curl --version
----

=== Cloning the Site source repository

[IMPORTANT]
--
Clone Site's repository to your computer, and change the current directory to `site`.

----
$ git clone https://github.com/juxt-site/site
$ cd site
----
--

=== Set SITE_HOME and PATH

Set the SITE_HOME environment variable to the location where you have
cloned the Site git repo.

[IMPORTANT]
--
Add `$SITE_HOME/server/bin` and `$SITE_HOME/client/bin` to your `PATH` environment variable.
--

For example, with Bash, you would put something like the following in your `.bashrc` file and restart the shell:

----
export SITE_HOME=$HOME/src/github.com/juxt-site/site
export PATH=$SITE_HOME/client/bin:$SITE_HOME/server/bin:$PATH
----

=== Copy Site's configuration file

The Site instance requires a configuration file, which specifies important settings such as the base-uri used for new resources, port numbers and the database configuration.

[IMPORTANT]
--
Copy `server/etc/config.edn` to `$HOME/.config/site/config.edn`:

----
mkdir -p $HOME/.config/site
cp $SITE_HOME/server/etc/config.edn $HOME/.config/site/config.edn
----
--

Review the config at `$HOME/.config/site/config.edn` and make any appropriate modifications.

=== Start the Site instance

It is now time to start the Site instance, which runs on a JVM on your local machine.

[IMPORTANT]
--
Start the Site instance:

----
$SITE_HOME/server/bin/site-server
----
--

Check the server starts up by looking out for a message on the console similar to the following:

----
Site by JUXT. Copyright (c) 2020-2023, JUXT LTD.
2023-05-22 11:02:46.508:INFO::main: Logging initialized @5804ms to org.eclipse.jetty.util.log.StdErrLog
...
2023-06-21 12:36:00,180 INFO  juxt.site.main: System started and ready... [ thread=main]
----

Check the server is up by calling an endpoint with curl:

----
curl http://localhost:4444/_site/healthcheck
----

This should report:

----
Site OK!
----

=== Bootstrapping Site resources

In this section we introduce `sitectl`.
This is a command line tool that connects to a running Site instance on same host, via a locally-bound REPL running on port 50505.
It is used only for administrative operations.

Clear out any existing resources from Site.
This isn't strictly necessary if you haven't installed Site before, but is worth knowing in case you want to start over.

----
sitectl reset
----

Next we must bootstrap Site by deploying a minimal set of resources.

[IMPORTANT]
--
Bootstrap your Site instance:

----
sitectl install-group juxt/site/bootstrap
----
--

When prompted, accept the offer to install the resources.

You can now inspect your Site instance's resources.

----
sitectl ls
----

These are a minimal set of resources that allow us to create operations and grant permissions to use them.

=== Adding API support

We can add some operations that allow us to build an API:

[IMPORTANT]
--
Install the operations needed to build an API

----
sitectl install-group juxt/site/api-operations
----
--

=== Install the System API

Site can be configured remotely, via its own API, which we need to install now.

[IMPORTANT]
--
Install the Site System API

----
sitectl install-group juxt/site/system-api
----
--

=== Configure Site to issue bearer tokens

Many of the operations of the System API can only be accessed by a client that makes requests with a bearer token.
Bearer tokens are signed JSON Web Tokens (JWTs).

We must first generate a keypair that Site can use to sign the JWTs that it will issue.

[IMPORTANT]
--
Generate a new keypair:

----
sitectl new-keypair
----
--

NOTE: You can also use `sitectl new-keypair` whenever you want to rotate the keypair.

We must also install a token endpoint for a client to be able to request a bearer token.

[IMPORTANT]
--
Install a token endpoint for issuing bearer tokens:

----
sitectl install-group juxt/site/oauth-token-endpoint
----
--

=== Register some applications

Site comes with a command line application that can be used to configure a Site instance.
There is also a web UI which does the same.

We must register one or both of these applications before they can be used.

[IMPORTANT]
--
Register the command-line application and InSite UI

----
sitectl install-group juxt/site/system-client --client-id site-cli
sitectl install-group juxt/site/system-client --client-id insite
----
--

=== Preparing to use site-cli

The command line client has a default client_id of `site-cli`.

[IMPORTANT]
--
Extract the client secret for this client_id:

----
sitectl client-secret --save site-cli
----
--

NOTE: Adding the `--save` option has the effect of writing the value of `client_secret` (for the `site-cli` application) to a cached area on your local disk (usually `$HOME/.cache/site/client-secrets/site-cli`).

We are now finished with `sitectl` and can continue configuring Site remotely if you like.
If you do want to continue setting up Site on a remote machine you'll need to take a note of the client-secret.

=== Configuring site-cli

Create a file called `$HOME/.config/site/site-cli.yaml` with the following content:

----
---
resource_server:
  base_uri: http://localhost:4444

authorization_server:
  base_uri: http://localhost:4440

client_credentials:
  ask_for_client_secret: true
  cache_client_secret: true

curl:
  save_bearer_token_to_default_config_file: true
----

=== Using the Site command line tool

Get a bearer token, saved to .curlrc

----
site request-token
----

This should output something similar to the following:

----
Reading client-secret from /home/mal/.cache/site/client-secrets/site-cli
Access token saved, expires in 86400 seconds
----

Check a bearer token is current

----
site check-token
----

Install an introspection endpoint (Optional)

----
sitectl install-group juxt/site/oauth-introspection-endpoint
----

Check the token again.

----
site check-token
----

=== Adding users

Add a new user.

----
curl --json @client/curl/test-user.json http://localhost:4444/_site/users
----

Check the user has been added

----
curl -H accept:application/json http://localhost:4444/_site/users
----

Add a password for the user

----
(coming soon)
----

Test the list of users

----
curl -i -H accept:application/json http://localhost:4444/_site/users
----

=== Swagger UI

Install the OpenAPI support

----
sitectl install-group juxt/site/openapi
----

Register the swagger-ui app

----
sitectl register-application swagger-ui
----

Test that the System API has been installed by opening a browser at https://petstore.swagger.io/?url=http://localhost:4444/_site/openapi.json

With a browser, navigate to https://petstore.swagger.io/?url=http://localhost:4444/_site/openapi.json
. Click on /whoami, 'Try it out' and 'Execute' (this should yield a `401 Error: Unauthorized`)
. Click on 'Authorize', ensure client_id is set to `swagger-ui`, under Scopes, click on `select-all`
. If the login succeeded, click on `Close`.
. Click again on `Execute` of the `/whoami` resource. This should now return a 200.

// Local Variables:
// mode: outline
// outline-regexp: "[=]+"
// End:
