= Getting Started
:toc: left

Follow this guide to get up-and-running with your very own Site instance.

=== Checking dependencies

Before we get started, let's check some dependencies.

Ensure you have https://github.com/babashka/babashka[Babashka] version v1.1.172 or later installed:

----
bb --version
babashka v1.1.172
----

Ensure you have https://clojure.org/[Clojure] version v1.11 or later installed:

----
clj --version
Clojure CLI version 1.11.1.1273
----

Ensure you have https://github.com/charmbracelet/gum/[`gum`] installed.

For exampe, on Arch Linux you can install `gum` with the following:

----
pacman -S gum
----

=== Starting up a Site instance

Clone this repository to your computer, cd into the `site` directory:

----
$ git clone https://github.com/juxt-site/site
$ cd site
----

Set the SITE_HOME environment variable to the location where you have
cloned the Site git repo.

Add `$SITE_HOME/server/bin` and `$SITE_HOME/client/bin` to your `PATH` environment variable.

Copy `server/etc/config.edn` to `$HOME/.config/site/config.edn`:

----
mkdir -p $HOME/.config/site
cp server/etc/config.edn $HOME/.config/site/config.edn
----

Review the config at `$HOME/.config/site/config.edn` and make any appropriate modifications.

Start the Site instance:

----
server/bin/site-server
----

Check the server starts up.

----
Site by JUXT. Copyright (c) 2020-2023, JUXT LTD.
2023-05-22 11:02:46.508:INFO::main: Logging initialized @5804ms to org.eclipse.jetty.util.log.StdErrLog
----

Check the server is up by calling an endpoint with curl:

----
curl http://localhost:4444/_site/healthcheck
----

This should report:

----
Site OK!
----

=== Installing Site resources

In this section we introduce `sitectl`.
This is a command line tool that connects to a running Site instance on same host, via a locally-bound REPL.
It is only for administrative operations.

Clear out any existing resources from Site.
This isn't strictly necessary if you haven't installed Site before, but is worth knowing in case you want to start over.

----
sitectl reset
----

Bootstrap your Site instance by deploying a minimal set of resources.

----
sitectl install-group juxt/site/bootstrap
----

When prompted, accept the offer to install the resources.

You can now inspect your Site instance's resources.

----
sitectl ls
----

These are a minimal set of resources that allow us to create operations and grant permissions to use them.

We can add some operations that allow us to build an API:

----
sitectl install-group juxt/site/api-operations
----

Install the Site System API

----
sitectl install-group juxt/site/system-api
----

Much of the System API can only be accessed by a client that makes requests with a bearer token.
Bearer tokens are signed JSON Web Tokens (JWTs).

We must generate a keypair that Site can use to sign these JWTs.

----
sitectl new-keypair
----

NOTE: You can also use `sitectl new-keypair` whenever you want to rotate the keypair.

We must also install a token endpoint for a client to be able to request a bearer token.

----
sitectl install-group juxt/site/oauth-token-endpoint
----

== Preparing the Site command line tool

Site comes with a command line application that can be used to configure a Site instance.
However, if you prefer to use a web UI, you may opt to do that instead of the command line application.

=== Register the command line application with Site

Register the command-line app

----
sitectl install-group juxt/site/site-cli-client
----

The command line client has a default client_id of `site-cli`.

Extract the client secret for this client_id:

----
sitectl client-secret --save site-cli
----

NOTE: Adding the `--save` option has the effect of writing the value of `client_secret` (for the `site-cli` application) to a cached area on your local disk (usually `$HOME/.cache/site/client-secrets/site-cli`).

We are now finished with `sitectl` and can continue configuring Site remotely if you like.
If you do want to continue setting up Site on a remote machine you'll need to take a note of the client-secret.

=== Configuring site-cli

Create a file called `$HOME/.config/site/site-cli.yaml` with the following content:

----
---
resource_server:
  base_uri: http://localhost:4444

authorization_server:
  base_uri: http://localhost:4440

client_credentials:
  ask_for_client_secret: true
  cache_client_secret: true

curl:
  save_bearer_token_to_default_config_file: true
----

== Using the Site command line tool

Get a bearer token, saved to .curlrc

----
site request-token
----

This should output something similar to the following:

----
Reading client-secret from /home/mal/.cache/site/client-secrets/site-cli
Access token saved, expires in 86400 seconds
----

Check a bearer token is current

----
site check-token
----

Install an introspection endpoint (Optional)

----
sitectl install-group juxt/site/oauth-introspection-endpoint
----

Check the token again.

----
site check-token
----

=== Adding users

Add a new user.

----
curl --json @client/curl/test-user.json http://localhost:4444/_site/users
----

Check the user has been added

----
curl -H accept:application/json http://localhost:4444/_site/users
----

Add a password for the user

----
(coming soon)
----

Test the list of users

----
curl -i -H accept:application/json http://localhost:4444/_site/users
----

=== Swagger UI

Install the OpenAPI support

----
sitectl install-group juxt/site/openapi
----

Register the swagger-ui app

----
sitectl register-application swagger-ui
----

Test that the System API has been installed by opening a browser at https://petstore.swagger.io/?url=http://localhost:4444/_site/openapi.json

With a browser, navigate to https://petstore.swagger.io/?url=http://localhost:4444/_site/openapi.json
. Click on /whoami, 'Try it out' and 'Execute' (this should yield a `401 Error: Unauthorized`)
. Click on 'Authorize', ensure client_id is set to `swagger-ui`, under Scopes, click on `select-all`
. If the login succeeded, click on `Close`.
. Click again on `Execute` of the `/whoami` resource. This should now return a 200.

== (Old instructions)

NOTE: We're keeping these instructions as they're useful if you want
to configure a reverse-proxy with proper hostnames.

If you're really keen, you can try out Site and use Swagger UI as a test client.
Follow these instructions:

. Install nginx - see link:doc/next/Installation.adoc[]
. `git clone https://github.com/juxt-site/swagger-ui`
. Install `mkcert` as per link:doc/next/Installation.adoc[]
. Create a cert: `mkcert data.site.test auth.site.test`
. Create a separate cert for the Swagger UI client: `mkcert swagger-ui.site.test`
. Move the generated certs (and associated key files) to your `/etc/nginx/` directory.
. Add the following sub-section to the `http` section of your `/etc/nginx/nginx.conf` file
+
----
    server {
        listen       443 ssl;
        server_name  data.site.test auth.site.test;

        ssl_certificate      data.site.test+1.pem;
        ssl_certificate_key  data.site.test+1-key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
           proxy_pass	http://localhost:2021;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
----
. Add the following sub-section to the `http` section of your `/etc/nginx/nginx.conf` file
+
----
    server {
        listen       443 ssl;
        server_name  swagger-ui.site.test;

        ssl_certificate      swagger-ui.site.test.pem;
        ssl_certificate_key  swagger-ui.site.test-key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
	  # Replace this with the absolute path of the dist subdir of the swagger-ui clone
	  root swagger-ui/dist/;
        }
    }
----
. As noted, replace the `swagger-ui/dist/` line with the right location on your system.
. Make sure the `ssl_certificate` and `ssl_certificate_key` entries match the filenames of your cert and key files.
. Check nginx config with `nginx -t` first, which will also check the filenames are correct
. Start nginx, e.g. `sudo systemctl start nginx`
. Start a REPL using the provided deps.edn in the usual way.
. Go to the file `src/juxt/site/repl.clj` and search for `:openid/register-user`. Edit the settings there according to your GitHub username.
. From the REPL, enter `(init)`. Alternatively, `rlwrap ncat localhost 50505` and type `:init` - this step will require network access as it downloads issuer configuration and keys.
. Browse to https://swagger-ui.site.test/
. Click on the green `Authorize` button
. Initially this will redirect you to Auth0. Click on the Github icon which will take you to Github. You'll need to allow Github to authorize Auth0 to access your basic profile details. These are used to match the identity you've registered with `:open/register-user`.
. You should now be able to 'try out' the API operations in the Swagger UI.
