= Protecting Resources
:toc: left

== Introduction

For many systems, it's necessary to protect resources from access and modification from unauthorized users.

In this chapter we will create an Operation for creating protected resources.
These preliminaries will be useful later on as we explore different approaches to authentication.

[[publishing-protected-resources]]
== Create the Operation to create a protected resource

We'll need an Operation to create a protected resource. This is demonstrated in
<<creating-an-operation-to-create-a-protected-resource>>.

[[creating-an-operation-to-create-a-protected-resource]]
.Creating an Operation to create a protected resource
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-operation-put-immutable-protected-resource!,indent=0]
----

<1> Users making a GET request to this resource will require a permission to
perform the Operation `+https://site.test/operations/get-protected-resource+`. This
Operation doesn't yet exist (but we'll create it in
<<creating-operation-get-protected-resource>>).

<2> We'll repeat our usual RBAC policy for this Operation: we make this Operation
accessible if a Permission exists that permits Users in a particular role to
perform this Operation.

As per our Operation's rules, we'll need to grant a Permission so that our REPL user can perform it:

[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-put-immutable-protected-resource!,indent=0]
----
====

[IMPORTANT]
--

Copy the code snippets in <<creating-an-operation-to-create-a-protected-resource>>
into a REPL, edit as required and evaluate.

--

In <<creating-an-operation-to-create-a-protected-resource>>, we restricted access
to the resource to those Users who are authorized to perform the
`+https://site.test/operations/get-protected-resource+`
Operation. <<creating-operation-get-protected-resource>> demonstrates the creation
this Operation.

[[creating-operation-get-protected-resource]]
.Creating the `get-protected-resource` Operation
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-operation-get-protected-resource!,indent=0]
----

<1> The Permission must directly reference the User.

<2> The Permission must _also_ directly reference the Resource that is being
protected. There are no roles used in this example, Permissions must exist for
every combination of User and Resource. Note, this may not be practical for many
systems, but works for these authentication examples.

====

[IMPORTANT]
--

Copy the code in <<creating-operation-get-protected-resource>> into a REPL, edit as
required and evaluate.

--

Now we have created the Operations necessary to protect resources from unauthorized
Users, we can illustrate different approaches to User authentication.



////
Now to create a protected resource.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-immutable-protected-resource!,indent=0]
----

[IMPORTANT]
--
Do it
--

Let's try to access the protected resource.

----
curl -i https://site.test/protected.html
----

We should get a response with a 401 status. We're not authorized to access this
resource.

----
HTTP/1.1 401 Unauthorized
Server: nginx/1.20.2
Date: Sat, 09 Apr 2022 08:12:40 GMT
Content-Type: text/plain;charset=utf-8
Content-Length: 14
Connection: keep-alive
site-request-id: https://site.test/_site/requests/980cf294f4ab87688c65581d
permissions-policy: interest-cohort=()

Unauthorized
----
====

////
