= Users Revisited
:toc: left
:experimental:

In <<ch-users>> we put Documents directly the database to represent an initial User.

Operations can't be invoked without a User, yet Operations, but Operations are required
to create Users. We had a chicken-and-egg situation that we resolved by directly
inserting the first user by hand.

However, now that we have built the capability to create Operations and
Permissions, we can build the Operations to create new Users, User Identities and
Subjects. That's the subject of this chapter.

== Create an operation to create a user

An Operation to create a User should take a new Document describing the User,
validate that the `:juxt.site.alpha/type` attribute is set to
`https://meta.juxt.site/pass/user` and other required checks. For example, a
User might be required to have a name and other required attributes.

<<ex-create-operation-put-user>> demonstrates the creation of an Operation that
fulfils these criteria.

[[ex-create-operation-put-user]]
.Creating an operation to put a user
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-operation-put-user!,indent=0]
----

Here we grant the REPL user access to perform this Operation.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-invoke-operation-put-user!,indent=0]
----

<1> Check the format of the id.

<2> Check the type.

<3> Default the type, if not given in the argument.

<4> Allow the user details to be retrieved via the GET method, with the
`https://site.test/operations/get-user` Operation.

<5> Ensure only roles with a Permission are able to perform this Operation.

====

[IMPORTANT]
--
Copy the code in <<ex-create-operation-put-user>>, paste it into a REPL and evaluate.
--

== Create an Operation to create a User Identity

In the same way, we may also need the ability to create a User Identity. For
this Operation it is important that the Document given in the document refers to
the User it is identifying.

See <<ex-create-operation-put-user-identity>> for a demonstration of creating and
permitting an Operation that meets these requirements.

[[ex-create-operation-put-user-identity]]
.Creating an Operation to put a User Identity
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-operation-put-user-identity!,indent=0]
----

Here we grant the REPL user access to perform this Operation.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-invoke-operation-put-user-identity!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<ex-create-operation-put-identity>>, paste it into a REPL and evaluate.
--

== Create an Operation to create an Subject

[[ex-create-operation-put-subject]]
.Creating an operation to put a subject
====
[source,clojure]
----
include::../../test/juxt/book.clj[tag=create-operation-put-subject!,indent=0]
----

Here we grant the REPL user access to perform this Operation.

[source,clojure]
----
include::../../test/juxt/book.clj[tag=grant-permission-to-invoke-operation-put-subject!,indent=0]
----
====

[IMPORTANT]
--
Copy the code in <<ex-create-operation-put-subject>>, paste it into a REPL and evaluate.
--
