name: CI

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        java-version: ["20"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.6
        with:
          cli: 1.10.3.1040
      - name: Checkout
        uses: actions/checkout@v2-beta

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Run tests not Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: make
        working-directory: server
        shell: bash

      - name: Run tests on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: make
        working-directory: server
        shell: powershell

